name: PHP Context-Aware Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Install PHP dependencies
        run: composer install

      - name: Install Python packages
        run: pip install PyGithub

      - name: Run Context-Aware Review
        run: php run_review.php

      - name: Post Feedback (Optional)
        run: python3 post_feedback.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
